default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: agile_gamification_development

test:
  <<: *default
  database: agile_gamification_test

production:
  <<: *default
  host:     <%= ENV['AGILE_GAMIFICATION_DATABASE_HOST'] %>
  database: <%= ENV['AGILE_GAMIFICATION_DATABASE_NAME'] %>
  username: <%= ENV['AGILE_GAMIFICATION_DATABASE_USERNAME'] %>
  port:     <%= ENV['AGILE_GAMIFICATION_DATABASE_PORT'] %>
  password: <%= ENV['AGILE_GAMIFICATION_DATABASE_PASSWORD'] %>
