default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: agile_gamification_development

test:
  <<: *default
  database: agile_gamification_test

production:
  <<: *default
  database: agile_gamification_production
  username: agile_gamification
  password: <%= ENV['AGILE_GAMIFICATION_DATABASE_PASSWORD'] %>
